### PR TITLE
Option to disable cookie auth 

### PR DESCRIPTION
**Pull request by faishal**
Do not set HM_DELEGATED_AUTH_CLIENT_ID if client id is empty to disable cookie auth

### CODE REVIEW

**Comment by faishal** [comment]
@joehoyle  : What should be the default value for that? Is it true by default ?

**Comment by roborourke** [comment]
@faishal we should keep the current default settings ideally, this PR should update the docs accordingly too.

@joehoyle can you provide some clearer instructions as to what you mean here?

**Comment by joehoyle** [comment]
yeah I think we should default an option `cookie` to `true`, because that's what it would have been previously. We don't _need_ to change upstream, as not defining `HM_DELEGATED_AUTH_CLIENT_ID` essentially just disabled cookie auth, so I'd just add code like this (and add a config for `cookie` that defaults to `true`: 

```php
if ( ! empty( $config['oauth2-client-id'] ) && ! empty( $config['cookie'] ) ) {
```

**Comment by roborourke** [comment]
Tagged 3.0.2 with this update

**Pull request merged**
